### ISSUE TITLE
having problem when try to koji build on upstream packages. /bin/bash: line 6: curl: command not found

### ISSUE THREAD

**Issue by YinThong** [clearlinux/koji-setup-scripts#5]
make[1]: Entering directory '/chroot_tmpdir/scmroot/telemetrics-client'
DEBUG util.py:399:  while read u; do \
DEBUG util.py:399:  	case "$u" in \
DEBUG util.py:399:  		"")    continue ;; \
DEBUG util.py:399:  		*://*) n="$u" ;; \
DEBUG util.py:399:  		*)     n="""/$u" ;; \
DEBUG util.py:399:  	esac; \
DEBUG util.py:399:  	if ! curl --fail -L -o `basename "$n"`  "$n"; then \
DEBUG util.py:399:  		echo "Failed to download $n"; \
DEBUG util.py:399:  		exit 1; \
DEBUG util.py:399:  	fi; \
DEBUG util.py:399:  done < upstream
DEBUG util.py:399:  /bin/bash: line 6: curl: command not found
DEBUG util.py:399:  Failed to download /3236765c83bb09a9928f838c88e31b19ef84132b/telemetrics-client-2.1.1.tar.gz
DEBUG util.py:399:  make[1]: *** [projects/common/Makefile.common:255: sources] Error 1

**Comment by YinThong** [comment]
@gtkramer suspect the bootstrap-build.sh need to add curl-bin into add-group-pkg -build build curl-bin.

**Comment by gtkramer** [comment]
Cannot reproduce.  Did a fresh deployment of koji on Clear Linux and this issue is not seen.
